// ============================================================
// choices.js – Antwort-Optionen je Flaggen-Nummer.
// Automatisch erzeugt am 2026-09-07 durch tools/generate_choices.mjs.
// Pro Nummer genau 5 Ländernamen; der ERSTE ist der richtige
// (die App mischt die Reihenfolge bei jeder Frage).
// Ablenker: ähnliche Flaggen, Nachbarn (Afrika/Südamerika/Asien),
// Rest zufällig – siehe tools/generate_choices.mjs.
// Bei Änderungen neu erzeugen mit:
//   node tools/generate_choices.mjs
// ============================================================
window.CHOICES = {
  1: ["Afghanistan","Zypern","Südkorea","Iran","Pakistan"],
  2: ["Ägypten","Jemen","Irak","Israel","Libyen"],
  3: ["Albanien","Kirgisistan","Volksrepublik China","Türkei","Peru"],
  4: ["Algerien","Italien","Libyen","Mali","Marokko"],
  5: ["Andorra","Rumänien","Moldau","Tschad","Libanon"],
  6: ["Angola","Demokratische Republik Kongo","Gabun","Namibia","Republik Kongo"],
  7: ["Antigua und Barbuda","Bhutan","Singapur","Panama","Iran"],
  8: ["Äquatorialguinea","Gabun","Kamerun","São Tomé und Príncipe","Niger"],
  9: ["Argentinien","Bolivien","Brasilien","Chile","Paraguay"],
  10: ["Armenien","Venezuela","Aserbaidschan","Georgien","Iran"],
  11: ["Aserbaidschan","Armenien","Georgien","Iran","Russland"],
  12: ["Äthiopien","Ghana","Dschibuti","Eritrea","Kenia"],
  13: ["Australien","Neuseeland","Iran","Katar","Jemen"],
  14: ["Bahamas","Kuba","Frankreich","Australien","Bulgarien"],
  15: ["Bahrain","Iran","Saudi-Arabien","Katar","Paraguay"],
  16: ["Bangladesch","Indien","Myanmar","Saudi-Arabien","Liberia"],
  17: ["Barbados","Tschad","Island","Togo","Nigeria"],
  18: ["Belarus","Malediven","Österreich","Israel","Eswatini"],
  19: ["Belgien","Tschad","Rumänien","Malawi","Frankreich"],
  20: ["Belize","St. Kitts und Nevis","Palästina","Chile","Grenada"],
  21: ["Benin","Burkina Faso","Niger","Nigeria","Togo"],
  22: ["Bhutan","Indien","Volksrepublik China","Thailand","Mauritius"],
  23: ["Bolivien","Ghana","Argentinien","Brasilien","Chile"],
  24: ["Bosnien und Herzegowina","Republik Kongo","Simbabwe","Dschibuti","Turkmenistan"],
  25: ["Botswana","Namibia","Sambia","Simbabwe","Südafrika"],
  26: ["Brasilien","Argentinien","Bolivien","Frankreich","Guyana"],
  27: ["Brunei","Malaysia","Ägypten","Papua-Neuguinea","Nepal"],
  28: ["Bulgarien","Russland","Serbien","Slowakei","Volksrepublik China"],
  29: ["Burkina Faso","Benin","Elfenbeinküste","Ghana","Mali"],
  30: ["Burundi","Demokratische Republik Kongo","Ruanda","Tansania","Bahrain"],
  31: ["Chile","Tschechien","Argentinien","Bolivien","Peru"],
  32: ["Costa Rica","Jamaika","Palästina","Österreich","Mauritius"],
  33: ["Dänemark","Guinea-Bissau","Volksrepublik China","Burundi","Suriname"],
  34: ["Demokratische Republik Kongo","Angola","Burundi","Kamerun","Republik Kongo"],
  35: ["Deutschland","Angola","Togo","Barbados","Panama"],
  36: ["Dominica","Bhutan","Katar","Grenada","Südafrika"],
  37: ["Dominikanische Republik","Trinidad und Tobago","Norwegen","Kenia","Naoero"],
  38: ["Dschibuti","Äthiopien","Eritrea","Somalia","Oman"],
  39: ["Ecuador","Kolumbien","Peru","Malediven","Tansania"],
  40: ["El Salvador","Honduras","Nicaragua","Demokratische Republik Kongo","Aserbaidschan"],
  41: ["Elfenbeinküste","Irland","Burkina Faso","Ghana","Guinea"],
  42: ["Eritrea","Äthiopien","Dschibuti","Sudan","Guyana"],
  43: ["Estland","Costa Rica","Sambia","Südkorea","Grenada"],
  44: ["Eswatini","Mosambik","Südafrika","Singapur","Madagaskar"],
  45: ["Fidschi","Föderierte Staaten von Mikronesien","Dschibuti","Belarus","Tansania"],
  46: ["Finnland","Japan","Italien","Vatikanstadt","Mauritius"],
  47: ["Föderierte Staaten von Mikronesien","St. Lucia","Somalia","Fidschi","Argentinien"],
  48: ["Frankreich","Mexiko","Italien","Eritrea","Pakistan"],
  49: ["Gabun","Angola","Äquatorialguinea","Kamerun","Republik Kongo"],
  50: ["Gambia","Senegal","Kenia","Tansania","Somalia"],
  51: ["Georgien","Tuvalu","Chile","Äquatorialguinea","Bulgarien"],
  52: ["Ghana","Bolivien","Äthiopien","Burkina Faso","Elfenbeinküste"],
  53: ["Grenada","Nigeria","San Marino","Kuba","Schweden"],
  54: ["Griechenland","Tschechien","Mexiko","Nordkorea","Russland"],
  55: ["Guatemala","Malaysia","Jamaika","Pakistan","Uganda"],
  56: ["Guinea","Mali","Senegal","Rumänien","Elfenbeinküste"],
  57: ["Guinea-Bissau","Guinea","Senegal","Trinidad und Tobago","Niederlande"],
  58: ["Guyana","Brasilien","Suriname","Venezuela","Eritrea"],
  59: ["Haiti","Liechtenstein","Finnland","Australien","Palau"],
  60: ["Honduras","El Salvador","Nicaragua","Laos","Trinidad und Tobago"],
  61: ["Indien","Niger","Ungarn","Afghanistan","Bangladesch"],
  62: ["Indonesien","Monaco","Polen","Singapur","Australien"],
  63: ["Irak","Ägypten","Jemen","Iran","Jordanien"],
  64: ["Iran","Tadschikistan","Ungarn","Afghanistan","Armenien"],
  65: ["Irland","Elfenbeinküste","Italien","Myanmar","Kambodscha"],
  66: ["Island","Slowenien","Andorra","Tonga","Schweden"],
  67: ["Israel","Ägypten","Jordanien","Libanon","Syrien"],
  68: ["Italien","Mexiko","Irland","Frankreich","Elfenbeinküste"],
  69: ["Jamaika","Namibia","Liberia","Simbabwe","St. Vincent und die Grenadinen"],
  70: ["Japan","Philippinen","Russland","Südkorea","Vereinigte Staaten"],
  71: ["Jemen","Ägypten","Irak","Oman","Saudi-Arabien"],
  72: ["Jordanien","Palästina","Vereinigte Arabische Emirate","Irak","Israel"],
  73: ["Kambodscha","Laos","Thailand","Vietnam","Senegal"],
  74: ["Kamerun","Äquatorialguinea","Gabun","Nigeria","Republik Kongo"],
  75: ["Kanada","Ghana","Tuvalu","Nepal","Komoren"],
  76: ["Kap Verde","Bahrain","Aserbaidschan","Italien","Palästina"],
  77: ["Kasachstan","Kirgisistan","Russland","Turkmenistan","Usbekistan"],
  78: ["Katar","Iran","Saudi-Arabien","Bahrain","Schweden"],
  79: ["Kenia","Äthiopien","Somalia","Sudan","Südsudan"],
  80: ["Kirgisistan","Volksrepublik China","Vietnam","Tunesien","Kasachstan"],
  81: ["Kiribati","Sri Lanka","Burkina Faso","Turkmenistan","Panama"],
  82: ["Kolumbien","Ecuador","Brasilien","Nicaragua","Panama"],
  83: ["Komoren","Frankreich","Madagaskar","Mosambik","Seychellen"],
  84: ["Kroatien","Paraguay","Niederlande","Ungarn","Jemen"],
  85: ["Kuba","Somalia","Vereinigtes Königreich","Russland","Türkei"],
  86: ["Kuwait","Irak","Iran","Saudi-Arabien","Sudan"],
  87: ["Laos","Kambodscha","Myanmar","Thailand","Vietnam"],
  88: ["Lesotho","Südafrika","Kambodscha","Südkorea","Mauretanien"],
  89: ["Lettland","Laos","Afghanistan","Bosnien und Herzegowina","Bahamas"],
  90: ["Libanon","Israel","Syrien","Japan","Uganda"],
  91: ["Liberia","Elfenbeinküste","Guinea","Sierra Leone","Senegal"],
  92: ["Libyen","Ägypten","Algerien","Niger","Sudan"],
  93: ["Liechtenstein","Haiti","Algerien","Sierra Leone","Polen"],
  94: ["Litauen","Venezuela","Armenien","Belize","Mosambik"],
  95: ["Luxemburg","Paraguay","Niederlande","Fidschi","Iran"],
  96: ["Madagaskar","Frankreich","Komoren","Mosambik","Seychellen"],
  97: ["Malawi","Mosambik","Sambia","Tansania","Indien"],
  98: ["Malaysia","Brunei","Indonesien","Philippinen","Singapur"],
  99: ["Malediven","Vereinigtes Königreich","Trinidad und Tobago","Island","Kambodscha"],
  100: ["Mali","Guinea","Senegal","Algerien","Burkina Faso"],
  101: ["Malta","Simbabwe","Litauen","Kenia","Eswatini"],
  102: ["Marokko","Trinidad und Tobago","Vietnam","Türkei","Volksrepublik China"],
  103: ["Marshallinseln","Demokratische Republik Kongo","Salomonen","Montenegro","Ruanda"],
  104: ["Mauretanien","Algerien","Mali","Senegal","Ruanda"],
  105: ["Mauritius","Frankreich","Malediven","Seychellen","Kuwait"],
  106: ["Mexiko","Italien","Frankreich","San Marino","Malta"],
  107: ["Moldau","Rumänien","Tschad","Andorra","Guinea"],
  108: ["Monaco","Polen","Singapur","Indonesien","Botswana"],
  109: ["Mongolei","Russland","Volksrepublik China","Indonesien","Gabun"],
  110: ["Montenegro","Vietnam","Kirgisistan","Volksrepublik China","Türkei"],
  111: ["Mosambik","Eswatini","Komoren","Malawi","Sambia"],
  112: ["Myanmar","Bangladesch","Indien","Laos","Thailand"],
  113: ["Namibia","Angola","Botswana","Sambia","Südafrika"],
  114: ["Naoero","Samoa","São Tomé und Príncipe","Kiribati","Belarus"],
  115: ["Nepal","Indien","Volksrepublik China","Sambia","Uruguay"],
  116: ["Neuseeland","Australien","Gabun","St. Kitts und Nevis","Griechenland"],
  117: ["Nicaragua","El Salvador","Honduras","Turkmenistan","Indonesien"],
  118: ["Niederlande","Paraguay","Ungarn","Kroatien","Indien"],
  119: ["Niger","Indien","Algerien","Benin","Burkina Faso"],
  120: ["Nigeria","Benin","Kamerun","Niger","São Tomé und Príncipe"],
  121: ["Nordkorea","Russland","Südkorea","Volksrepublik China","Usbekistan"],
  122: ["Nordmazedonien","Vietnam","Malta","Bangladesch","Burkina Faso"],
  123: ["Norwegen","Libanon","Guyana","Angola","Osttimor"],
  124: ["Oman","Iran","Jemen","Saudi-Arabien","Vereinigte Arabische Emirate"],
  125: ["Österreich","Japan","Guinea","Schweiz","Aserbaidschan"],
  126: ["Osttimor","Marokko","Australien","Indonesien","Vietnam"],
  127: ["Pakistan","Afghanistan","Indien","Iran","Volksrepublik China"],
  128: ["Palästina","Jordanien","Vereinigte Arabische Emirate","Ägypten","Israel"],
  129: ["Palau","Belgien","Ghana","Nordkorea","Australien"],
  130: ["Panama","St. Vincent und die Grenadinen","Kap Verde","Senegal","Gambia"],
  131: ["Papua-Neuguinea","Angola","Vereinigte Staaten","Tschad","Kenia"],
  132: ["Paraguay","Niederlande","Kroatien","Ungarn","Argentinien"],
  133: ["Peru","Bolivien","Brasilien","Chile","Ecuador"],
  134: ["Philippinen","Indonesien","Japan","Malaysia","Palau"],
  135: ["Polen","Monaco","Singapur","Indonesien","Tonga"],
  136: ["Portugal","Kuba","Bahrain","Kasachstan","Kroatien"],
  137: ["Republik Kongo","Angola","Demokratische Republik Kongo","Gabun","Kamerun"],
  138: ["Ruanda","Burundi","Demokratische Republik Kongo","Tansania","Uganda"],
  139: ["Rumänien","Tschad","Moldau","Andorra","Guinea"],
  140: ["Russland","Serbien","Bulgarien","Slowakei","Slowenien"],
  141: ["Salomonen","Marshallinseln","Tansania","Namibia","Simbabwe"],
  142: ["Sambia","Angola","Botswana","Demokratische Republik Kongo","Malawi"],
  143: ["Samoa","Trinidad und Tobago","Marokko","Uruguay","Brasilien"],
  144: ["San Marino","Litauen","Palästina","Gabun","Elfenbeinküste"],
  145: ["São Tomé und Príncipe","Äquatorialguinea","Gabun","Nigeria","Frankreich"],
  146: ["Saudi-Arabien","Ägypten","Bahrain","Irak","Iran"],
  147: ["Schweden","St. Kitts und Nevis","Russland","Bahrain","Komoren"],
  148: ["Schweiz","Mosambik","Island","Schweden","Burkina Faso"],
  149: ["Senegal","Guinea","Mali","Gambia","Guinea-Bissau"],
  150: ["Serbien","Slowakei","Russland","Bulgarien","Burkina Faso"],
  151: ["Seychellen","Frankreich","Komoren","Madagaskar","Mauritius"],
  152: ["Sierra Leone","Usbekistan","Guinea","Liberia","Malediven"],
  153: ["Simbabwe","Botswana","Mosambik","Sambia","Südafrika"],
  154: ["Singapur","Polen","Monaco","Indonesien","Malaysia"],
  155: ["Slowakei","Serbien","Russland","Bulgarien","Uganda"],
  156: ["Slowenien","Russland","Kambodscha","Vereinigte Staaten","Kuwait"],
  157: ["Somalia","Äthiopien","Dschibuti","Kenia","Föderierte Staaten von Mikronesien"],
  158: ["Spanien","Volksrepublik China","Estland","Suriname","Kuwait"],
  159: ["Sri Lanka","Indien","Andorra","Sierra Leone","Tuvalu"],
  160: ["St. Kitts und Nevis","Vanuatu","Saudi-Arabien","Nigeria","Estland"],
  161: ["St. Lucia","Föderierte Staaten von Mikronesien","Dominikanische Republik","Senegal","Moldau"],
  162: ["St. Vincent und die Grenadinen","Tschechien","Lesotho","Suriname","Ägypten"],
  163: ["Südafrika","Botswana","Eswatini","Lesotho","Mosambik"],
  164: ["Sudan","Ägypten","Äthiopien","Demokratische Republik Kongo","Eritrea"],
  165: ["Südkorea","Afghanistan","Japan","Nordkorea","Volksrepublik China"],
  166: ["Südsudan","Äthiopien","Demokratische Republik Kongo","Kenia","Sudan"],
  167: ["Suriname","Brasilien","Frankreich","Guyana","Liechtenstein"],
  168: ["Syrien","Irak","Israel","Jordanien","Libanon"],
  169: ["Tadschikistan","Iran","Afghanistan","Kirgisistan","Usbekistan"],
  170: ["Tansania","Burundi","Demokratische Republik Kongo","Kenia","Malawi"],
  171: ["Thailand","Kambodscha","Laos","Malaysia","Myanmar"],
  172: ["Togo","Benin","Burkina Faso","Ghana","Türkei"],
  173: ["Tonga","Kiribati","Norwegen","Äthiopien","Frankreich"],
  174: ["Trinidad und Tobago","Marokko","Vietnam","Samoa","Malediven"],
  175: ["Tschad","Rumänien","Moldau","Andorra","Kamerun"],
  176: ["Tschechien","Chile","Singapur","Türkei","Jordanien"],
  177: ["Tunesien","Volksrepublik China","Türkei","Vietnam","Kirgisistan"],
  178: ["Türkei","Volksrepublik China","Vietnam","Tunesien","Marokko"],
  179: ["Turkmenistan","Afghanistan","Iran","Kasachstan","Usbekistan"],
  180: ["Tuvalu","Demokratische Republik Kongo","Somalia","Antigua und Barbuda","Vietnam"],
  181: ["Uganda","Demokratische Republik Kongo","Kenia","Ruanda","Sudan"],
  182: ["Ukraine","Nicaragua","Bangladesch","Mongolei","Slowenien"],
  183: ["Ungarn","Niederlande","Indien","Iran","Paraguay"],
  184: ["Uruguay","Argentinien","Brasilien","Salomonen","Guatemala"],
  185: ["Usbekistan","Sierra Leone","Afghanistan","Kasachstan","Kirgisistan"],
  186: ["Vanuatu","St. Kitts und Nevis","Burkina Faso","Estland","Bahamas"],
  187: ["Vatikanstadt","Panama","Mexiko","Litauen","Monaco"],
  188: ["Venezuela","Armenien","Litauen","Brasilien","Dominica"],
  189: ["Vereinigte Arabische Emirate","Palästina","Jordanien","Iran","Oman"],
  190: ["Vereinigte Staaten","Papua-Neuguinea","Gabun","Island","Südsudan"],
  191: ["Vereinigtes Königreich","Zentralafrikanische Republik","Kroatien","Botswana","Dschibuti"],
  192: ["Vietnam","Volksrepublik China","Türkei","Marokko","Tunesien"],
  193: ["Volksrepublik China","Türkei","Vietnam","Tunesien","Kirgisistan"],
  194: ["Zentralafrikanische Republik","Demokratische Republik Kongo","Kamerun","Republik Kongo","Sudan"],
  195: ["Zypern","Afghanistan","Japan","Südkorea","Indien"],
};
